---

- name: update www-data shell
  user: name=www-data shell=/bin/bash home=/var/www

- name: set correct permissions for ssh dir
  file: path=/var/www/.ssh owner=www-data group=www-data mode=0700 state=directory

- name: create php socket directory and set permission to www-data
  file: path=/var/run/php/ owner=www-data group=www-data mode=0700 state=directory
